Time taken to run the queries on ./repositories/Django/thread3/AlbertoZerbinati_sentag/AlbertoZerbinati-sentag-93cb171: 325.14 seconds.
Time taken to run the queries on ./repositories/Django/thread3/AnantShankhdhar_codeforces-crawler/AnantShankhdhar-codeforces-crawler-b1f2203: 375.715 seconds.
Analysis failed for: ./repositories/Django/thread3/Baljan_cafesys/Baljan-cafesys-d37e5a1 Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/Baljan_cafesys/Baljan-cafesys-d37e5a1 -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/Baljan_cafesys/Baljan-cafesys-d37e5a1: 311.837 seconds.
Analysis failed for: ./repositories/Django/thread3/Battery-Intelligence-Lab_galv/Battery-Intelligence-Lab-galv-118a8a1 Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/Battery-Intelligence-Lab_galv/Battery-Intelligence-Lab-galv-118a8a1 -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/Battery-Intelligence-Lab_galv/Battery-Intelligence-Lab-galv-118a8a1: 403.162 seconds.
Analysis failed for: ./repositories/Django/thread3/BitByte-TPC_gymkhana/BitByte-TPC-gymkhana-b7441f4 Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/BitByte-TPC_gymkhana/BitByte-TPC-gymkhana-b7441f4 -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/BitByte-TPC_gymkhana/BitByte-TPC-gymkhana-b7441f4: 276.607 seconds.
Time taken to run the queries on ./repositories/Django/thread3/ChatFAQ_ChatFAQ/ChatFAQ-ChatFAQ-d0e9979: 435.58 seconds.
Analysis failed for: ./repositories/Django/thread3/City-of-Helsinki_tunnistamo/City-of-Helsinki-tunnistamo-d1c8ab6 Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/City-of-Helsinki_tunnistamo/City-of-Helsinki-tunnistamo-d1c8ab6 -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/City-of-Helsinki_tunnistamo/City-of-Helsinki-tunnistamo-d1c8ab6: 389.021 seconds.
Time taken to run the queries on ./repositories/Django/thread3/City-of-Helsinki_yjdh/City-of-Helsinki-yjdh-a9fc149: 445.121 seconds.
Time taken to run the queries on ./repositories/Django/thread3/CroceRossaItaliana_jorvik/CroceRossaItaliana-jorvik-1c199ad: 434.43 seconds.
Time taken to run the queries on ./repositories/Django/thread3/Exifly_ApiVault/Exifly-ApiVault-5f370cb: 346.058 seconds.
Time taken to run the queries on ./repositories/Django/thread3/HermanMartinus_bearblog/HermanMartinus-bearblog-9c158ec: 321.398 seconds.
Time taken to run the queries on ./repositories/Django/thread3/HewlettPackard_squest/HewlettPackard-squest-dc6c147: 360.65 seconds.
Analysis failed for: ./repositories/Django/thread3/Hopetree_izone/Hopetree-izone-c4a40f6 Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/Hopetree_izone/Hopetree-izone-c4a40f6 -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/Hopetree_izone/Hopetree-izone-c4a40f6: 352.418 seconds.
Analysis failed for: ./repositories/Django/thread3/ICIJ_prophecies/ICIJ-prophecies-1068aa7 Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/ICIJ_prophecies/ICIJ-prophecies-1068aa7 -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/ICIJ_prophecies/ICIJ-prophecies-1068aa7: 312.077 seconds.
Analysis failed for: ./repositories/Django/thread3/JasurbekNURBOYEV_hops/JasurbekNURBOYEV-hops-c0a1dfe Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/JasurbekNURBOYEV_hops/JasurbekNURBOYEV-hops-c0a1dfe -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/JasurbekNURBOYEV_hops/JasurbekNURBOYEV-hops-c0a1dfe: 336.055 seconds.
Time taken to run the queries on ./repositories/Django/thread3/KSG-IT_ksg-nett/KSG-IT-ksg-nett-9b1ce68: 470.089 seconds.
Analysis failed for: ./repositories/Django/thread3/Katharine_ponytone/Katharine-ponytone-8c4047e Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/Katharine_ponytone/Katharine-ponytone-8c4047e -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/Katharine_ponytone/Katharine-ponytone-8c4047e: 334.219 seconds.
Failed to execute the query: CSRF/un_disabled_wtf_csrf_check on repository: ./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79 Reason: Error: spawnSync /bin/sh ETIMEDOUT
Failed to execute the query: CSRF/un_using_csrf_exempt on repository: ./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79 Reason: Error: Command failed: codeql query run --database=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database --output=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-results/CSRF/un_using_csrf_exempt.bqrs --threads=11 ../Flask_Queries/CSRF/un_using_csrf_exempt.ql
A fatal error occurred: Error initializing the IMB disk cache: the cache directory is already locked by another running process. Only one instance of the IMB can access a cache directory at a time. The lock file is located at /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database/db-python/default/cache/.lock
(eventual cause: OverlappingFileLockException)

Failed to execute the query: CSRF/un_using_csrf_protect on repository: ./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79 Reason: Error: Command failed: codeql query run --database=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database --output=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-results/CSRF/un_using_csrf_protect.bqrs --threads=11 ../Flask_Queries/CSRF/un_using_csrf_protect.ql
A fatal error occurred: Error initializing the IMB disk cache: the cache directory is already locked by another running process. Only one instance of the IMB can access a cache directory at a time. The lock file is located at /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database/db-python/default/cache/.lock
(eventual cause: OverlappingFileLockException)

Failed to execute the query: CSRF/un_using_flaskform on repository: ./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79 Reason: Error: Command failed: codeql query run --database=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database --output=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-results/CSRF/un_using_flaskform.bqrs --threads=11 ../Flask_Queries/CSRF/un_using_flaskform.ql
A fatal error occurred: Error initializing the IMB disk cache: the cache directory is already locked by another running process. Only one instance of the IMB can access a cache directory at a time. The lock file is located at /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database/db-python/default/cache/.lock
(eventual cause: OverlappingFileLockException)

Failed to execute the query: CSRF/un_using_flaskwtf_csrf_protection on repository: ./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79 Reason: Error: Command failed: codeql query run --database=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database --output=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-results/CSRF/un_using_flaskwtf_csrf_protection.bqrs --threads=11 ../Flask_Queries/CSRF/un_using_flaskwtf_csrf_protection.ql
A fatal error occurred: Error initializing the IMB disk cache: the cache directory is already locked by another running process. Only one instance of the IMB can access a cache directory at a time. The lock file is located at /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database/db-python/default/cache/.lock
(eventual cause: OverlappingFileLockException)

Failed to execute the query: CSRF/un_using_wtforms_csrf_protection on repository: ./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79 Reason: Error: Command failed: codeql query run --database=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database --output=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-results/CSRF/un_using_wtforms_csrf_protection.bqrs --threads=11 ../Flask_Queries/CSRF/un_using_wtforms_csrf_protection.ql
A fatal error occurred: Error initializing the IMB disk cache: the cache directory is already locked by another running process. Only one instance of the IMB can access a cache directory at a time. The lock file is located at /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database/db-python/default/cache/.lock
(eventual cause: OverlappingFileLockException)

Failed to execute the query: CSRF/un_changing_csrf_protected_methods on repository: ./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79 Reason: Error: Command failed: codeql query run --database=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database --output=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-results/CSRF/un_changing_csrf_protected_methods.bqrs --threads=11 ../Flask_Queries/CSRF/un_changing_csrf_protected_methods.ql
A fatal error occurred: Error initializing the IMB disk cache: the cache directory is already locked by another running process. Only one instance of the IMB can access a cache directory at a time. The lock file is located at /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database/db-python/default/cache/.lock
(eventual cause: OverlappingFileLockException)

Failed to execute the query: CSRF/un_disabled_wtf_csrf on repository: ./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79 Reason: Error: Command failed: codeql query run --database=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database --output=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-results/CSRF/un_disabled_wtf_csrf.bqrs --threads=11 ../Flask_Queries/CSRF/un_disabled_wtf_csrf.ql
A fatal error occurred: Error initializing the IMB disk cache: the cache directory is already locked by another running process. Only one instance of the IMB can access a cache directory at a time. The lock file is located at /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database/db-python/default/cache/.lock
(eventual cause: OverlappingFileLockException)

Failed to execute the query: CSRF/un_setting_wtf_csrf_secret_key on repository: ./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79 Reason: Error: Command failed: codeql query run --database=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database --output=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-results/CSRF/un_setting_wtf_csrf_secret_key.bqrs --threads=11 ../Flask_Queries/CSRF/un_setting_wtf_csrf_secret_key.ql
A fatal error occurred: Error initializing the IMB disk cache: the cache directory is already locked by another running process. Only one instance of the IMB can access a cache directory at a time. The lock file is located at /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database/db-python/default/cache/.lock
(eventual cause: OverlappingFileLockException)

Failed to execute the query: CSRF/un_using_flaskform_with_csrf_disabled on repository: ./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79 Reason: Error: Command failed: codeql query run --database=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database --output=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-results/CSRF/un_using_flaskform_with_csrf_disabled.bqrs --threads=11 ../Flask_Queries/CSRF/un_using_flaskform_with_csrf_disabled.ql
A fatal error occurred: Error initializing the IMB disk cache: the cache directory is already locked by another running process. Only one instance of the IMB can access a cache directory at a time. The lock file is located at /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database/db-python/default/cache/.lock
(eventual cause: OverlappingFileLockException)

Failed to execute the query: Clear-permanent-session-on-logout/un_clear_session_on_logout on repository: ./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79 Reason: Error: Command failed: codeql query run --database=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database --output=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-results/Clear-permanent-session-on-logout/un_clear_session_on_logout.bqrs --threads=11 ../Flask_Queries/Clear-permanent-session-on-logout/un_clear_session_on_logout.ql
A fatal error occurred: Error initializing the IMB disk cache: the cache directory is already locked by another running process. Only one instance of the IMB can access a cache directory at a time. The lock file is located at /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database/db-python/default/cache/.lock
(eventual cause: OverlappingFileLockException)

Failed to execute the query: Logout-function-is-called/un_logout_function_is_called on repository: ./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79 Reason: Error: Command failed: codeql query run --database=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database --output=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-results/Logout-function-is-called/un_logout_function_is_called.bqrs --threads=11 ../Flask_Queries/Logout-function-is-called/un_logout_function_is_called.ql
A fatal error occurred: Error initializing the IMB disk cache: the cache directory is already locked by another running process. Only one instance of the IMB can access a cache directory at a time. The lock file is located at /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database/db-python/default/cache/.lock
(eventual cause: OverlappingFileLockException)

Failed to execute the query: Flask-login-session-protection/uf_session_protection_basic on repository: ./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79 Reason: Error: Command failed: codeql query run --database=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database --output=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-results/Flask-login-session-protection/uf_session_protection_basic.bqrs --threads=11 ../Flask_Queries/Flask-login-session-protection/uf_session_protection_basic.ql
A fatal error occurred: Error initializing the IMB disk cache: the cache directory is already locked by another running process. Only one instance of the IMB can access a cache directory at a time. The lock file is located at /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database/db-python/default/cache/.lock
(eventual cause: OverlappingFileLockException)

Skippable Query: sf_session_protection, Unskippable counterpart: uf_session_protection_basic
Skipped the query: Flask-login-session-protection/sf_session_protection in the repository: ./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79
Skippable Query: sf_session_protection_strong, Unskippable counterpart: uf_session_protection_basic
Skipped the query: Flask-login-session-protection/sf_session_protection_strong in the repository: ./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79
Failed to execute the query: Flask-login-session-protection/un_session_protection_basic_is_used on repository: ./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79 Reason: Error: Command failed: codeql query run --database=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database --output=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-results/Flask-login-session-protection/un_session_protection_basic_is_used.bqrs --threads=11 ../Flask_Queries/Flask-login-session-protection/un_session_protection_basic_is_used.ql
A fatal error occurred: Error initializing the IMB disk cache: the cache directory is already locked by another running process. Only one instance of the IMB can access a cache directory at a time. The lock file is located at /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database/db-python/default/cache/.lock
(eventual cause: OverlappingFileLockException)

Failed to execute the query: Incorrect-config-changes/un_incorrect_config_changes on repository: ./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79 Reason: Error: Command failed: codeql query run --database=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database --output=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-results/Incorrect-config-changes/un_incorrect_config_changes.bqrs --threads=11 ../Flask_Queries/Incorrect-config-changes/un_incorrect_config_changes.ql
A fatal error occurred: Error initializing the IMB disk cache: the cache directory is already locked by another running process. Only one instance of the IMB can access a cache directory at a time. The lock file is located at /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database/db-python/default/cache/.lock
(eventual cause: OverlappingFileLockException)

Failed to execute the query: Fresh-login-restrictions/un_no_fresh_login_checks on repository: ./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79 Reason: Error: Command failed: codeql query run --database=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database --output=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-results/Fresh-login-restrictions/un_no_fresh_login_checks.bqrs --threads=11 ../Flask_Queries/Fresh-login-restrictions/un_no_fresh_login_checks.ql
A fatal error occurred: Error initializing the IMB disk cache: the cache directory is already locked by another running process. Only one instance of the IMB can access a cache directory at a time. The lock file is located at /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database/db-python/default/cache/.lock
(eventual cause: OverlappingFileLockException)

Failed to execute the query: Login-restrictions/un_no_authentication_checks on repository: ./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79 Reason: Error: Command failed: codeql query run --database=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database --output=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-results/Login-restrictions/un_no_authentication_checks.bqrs --threads=11 ../Flask_Queries/Login-restrictions/un_no_authentication_checks.ql
A fatal error occurred: Error initializing the IMB disk cache: the cache directory is already locked by another running process. Only one instance of the IMB can access a cache directory at a time. The lock file is located at /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database/db-python/default/cache/.lock
(eventual cause: OverlappingFileLockException)

Failed to execute the query: Login-restrictions/un_no_authentication_checks_general on repository: ./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79 Reason: Error: Command failed: codeql query run --database=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database --output=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-results/Login-restrictions/un_no_authentication_checks_general.bqrs --threads=11 ../Flask_Queries/Login-restrictions/un_no_authentication_checks_general.ql
A fatal error occurred: Error initializing the IMB disk cache: the cache directory is already locked by another running process. Only one instance of the IMB can access a cache directory at a time. The lock file is located at /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database/db-python/default/cache/.lock
(eventual cause: OverlappingFileLockException)

Failed to execute the query: Secret-key/un_secret_key on repository: ./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79 Reason: Error: Command failed: codeql query run --database=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database --output=./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-results/Secret-key/un_secret_key.bqrs --threads=11 ../Flask_Queries/Secret-key/un_secret_key.ql
A fatal error occurred: Error initializing the IMB disk cache: the cache directory is already locked by another running process. Only one instance of the IMB can access a cache directory at a time. The lock file is located at /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79-database/db-python/default/cache/.lock
(eventual cause: OverlappingFileLockException)

Failed to execute the query: Explorative-queries/un_list_config_settings_from_env_var on repository: ./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79 Reason: Error: spawnSync /bin/sh ETIMEDOUT
Failed to execute the query: Explorative-queries/un_potential_false_positives on repository: ./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79 Reason: Error: spawnSync /bin/sh ETIMEDOUT
Time taken to run the queries on ./repositories/Django/thread3/Kushal997-das_Project-Guidance/Kushal997-das-Project-Guidance-890fd79: 13933.653 seconds.
Analysis failed for: ./repositories/Django/thread3/LDO-CERT_orochi/LDO-CERT-orochi-5c4b00a Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/LDO-CERT_orochi/LDO-CERT-orochi-5c4b00a -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/LDO-CERT_orochi/LDO-CERT-orochi-5c4b00a: 316.167 seconds.
Time taken to run the queries on ./repositories/Django/thread3/MRCIEU_temmpo/MRCIEU-temmpo-48b1239: 413.654 seconds.
Time taken to run the queries on ./repositories/Django/thread3/MuckRock_squarelet/MuckRock-squarelet-8f973f8: 400.996 seconds.
Analysis failed for: ./repositories/Django/thread3/NicolasLM_feedsubs/NicolasLM-feedsubs-aa41222 Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/NicolasLM_feedsubs/NicolasLM-feedsubs-aa41222 -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/NicolasLM_feedsubs/NicolasLM-feedsubs-aa41222: 365.424 seconds.
Time taken to run the queries on ./repositories/Django/thread3/PLUS-POSTECH_study.plus.or.kr/PLUS-POSTECH-study.plus.or.kr-f3e4322: 347.016 seconds.
Analysis failed for: ./repositories/Django/thread3/PokeAPI_pokeapi/PokeAPI-pokeapi-f0b5103 Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/PokeAPI_pokeapi/PokeAPI-pokeapi-f0b5103 -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/PokeAPI_pokeapi/PokeAPI-pokeapi-f0b5103: 306.122 seconds.
Time taken to run the queries on ./repositories/Django/thread3/PrrrStar_ProjectNP/PrrrStar-ProjectNP-f1d50fe: 310.933 seconds.
Analysis failed for: ./repositories/Django/thread3/RTIInternational_SMART/RTIInternational-SMART-d3fff6b Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/RTIInternational_SMART/RTIInternational-SMART-d3fff6b -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/RTIInternational_SMART/RTIInternational-SMART-d3fff6b: 462.962 seconds.
Time taken to run the queries on ./repositories/Django/thread3/ResidenciaTICBrisa_05_PipelineFinatec/ResidenciaTICBrisa-05_PipelineFinatec-b1bd510: 302.682 seconds.
Analysis failed for: ./repositories/Django/thread3/ResonantGeoData_ResonantGeoData/ResonantGeoData-ResonantGeoData-0188ec5 Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/ResonantGeoData_ResonantGeoData/ResonantGeoData-ResonantGeoData-0188ec5 -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/ResonantGeoData_ResonantGeoData/ResonantGeoData-ResonantGeoData-0188ec5: 398.249 seconds.
Analysis failed for: ./repositories/Django/thread3/SERVIR_ClimateSERV2/SERVIR-ClimateSERV2-d5eb09e Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/SERVIR_ClimateSERV2/SERVIR-ClimateSERV2-d5eb09e -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/SERVIR_ClimateSERV2/SERVIR-ClimateSERV2-d5eb09e: 398.028 seconds.
Analysis failed for: ./repositories/Django/thread3/SFDO-Tooling_MetaCI/SFDO-Tooling-MetaCI-46d69ca Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/SFDO-Tooling_MetaCI/SFDO-Tooling-MetaCI-46d69ca -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/SFDO-Tooling_MetaCI/SFDO-Tooling-MetaCI-46d69ca: 386.983 seconds.
Analysis failed for: ./repositories/Django/thread3/SalengNotLittleMeng_YundingFullStack/SalengNotLittleMeng-YundingFullStack-378095d Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/SalengNotLittleMeng_YundingFullStack/SalengNotLittleMeng-YundingFullStack-378095d -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/SalengNotLittleMeng_YundingFullStack/SalengNotLittleMeng-YundingFullStack-378095d: 321.544 seconds.
Time taken to run the queries on ./repositories/Django/thread3/StephenXie_ProjectAlpha/StephenXie-ProjectAlpha-2f4b83e: 240.17 seconds.
Time taken to run the queries on ./repositories/Django/thread3/Syslifters_sysreptor/Syslifters-sysreptor-7a80556: 386.935 seconds.
Analysis failed for: ./repositories/Django/thread3/Taycode_jumga/Taycode-jumga-77b9a87 Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/Taycode_jumga/Taycode-jumga-77b9a87 -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/Taycode_jumga/Taycode-jumga-77b9a87: 367.792 seconds.
Analysis failed for: ./repositories/Django/thread3/TencentBlueKing_bk-bcs/TencentBlueKing-bk-bcs-0c9b479 Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/TencentBlueKing_bk-bcs/TencentBlueKing-bk-bcs-0c9b479 -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/TencentBlueKing_bk-bcs/TencentBlueKing-bk-bcs-0c9b479: 295.419 seconds.
Analysis failed for: ./repositories/Django/thread3/TencentBlueKing_bk-log/TencentBlueKing-bk-log-3d3efef Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/TencentBlueKing_bk-log/TencentBlueKing-bk-log-3d3efef -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/TencentBlueKing_bk-log/TencentBlueKing-bk-log-3d3efef: 397.39 seconds.
Time taken to run the queries on ./repositories/Django/thread3/TencentBlueKing_blueking-paas/TencentBlueKing-blueking-paas-71e1652: 496.87 seconds.
Time taken to run the queries on ./repositories/Django/thread3/TiBillet_TiBillet/TiBillet-TiBillet-1ca7ccd: 340.847 seconds.
Time taken to run the queries on ./repositories/Django/thread3/Umuzi-org_Tilde/Umuzi-org-Tilde-68c10de: 461.031 seconds.
Analysis failed for: ./repositories/Django/thread3/UnBArqDsw2022-2_2022.2_G3_SpotHood/UnBArqDsw2022-2-2022.2_G3_SpotHood-82e9c47 Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/UnBArqDsw2022-2_2022.2_G3_SpotHood/UnBArqDsw2022-2-2022.2_G3_SpotHood-82e9c47 -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/UnBArqDsw2022-2_2022.2_G3_SpotHood/UnBArqDsw2022-2-2022.2_G3_SpotHood-82e9c47: 297.847 seconds.
Analysis failed for: ./repositories/Django/thread3/VTIvanov20_Vectra/VTIvanov20-Vectra-438c914 Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/VTIvanov20_Vectra/VTIvanov20-Vectra-438c914 -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/VTIvanov20_Vectra/VTIvanov20-Vectra-438c914: 300.898 seconds.
Time taken to run the queries on ./repositories/Django/thread3/XiaoMi_minos/XiaoMi-minos-164454a: 468.927 seconds.
Time taken to run the queries on ./repositories/Django/thread3/ancile-project_ancile/ancile-project-ancile-0dc9ba5: 420.846 seconds.
Time taken to run the queries on ./repositories/Django/thread3/apyb_associados/apyb-associados-6808db9: 301.214 seconds.
Time taken to run the queries on ./repositories/Django/thread3/bounswe_bounswe2017group5/bounswe-bounswe2017group5-6445474: 266.169 seconds.
Analysis failed for: ./repositories/Django/thread3/bram2w_baserow/bram2w-baserow-0718276 Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/bram2w_baserow/bram2w-baserow-0718276 -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/bram2w_baserow/bram2w-baserow-0718276: 587.825 seconds.
Time taken to run the queries on ./repositories/Django/thread3/cap-ntu_Video-to-Retail-Platform/cap-ntu-Video-to-Retail-Platform-757c68d: 633.233 seconds.
Analysis failed for: ./repositories/Django/thread3/celery_celery/celery-celery-46992a1 Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/celery_celery/celery-celery-46992a1 -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/celery_celery/celery-celery-46992a1: 434.09 seconds.
Time taken to run the queries on ./repositories/Django/thread3/chiraag-kakar_sharenlearn/chiraag-kakar-sharenlearn-8de9f92: 346.537 seconds.
Time taken to run the queries on ./repositories/Django/thread3/claudioavgo_triphelper/claudioavgo-triphelper-b1abc4f: 463.155 seconds.
Analysis failed for: ./repositories/Django/thread3/deardurham_dear-petition/deardurham-dear-petition-3814c36 Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/deardurham_dear-petition/deardurham-dear-petition-3814c36 -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/deardurham_dear-petition/deardurham-dear-petition-3814c36: 308.462 seconds.
Analysis failed for: ./repositories/Django/thread3/decompiler-explorer_decompiler-explorer/decompiler-explorer-decompiler-explorer-4f533aa Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/decompiler-explorer_decompiler-explorer/decompiler-explorer-decompiler-explorer-4f533aa -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/decompiler-explorer_decompiler-explorer/decompiler-explorer-decompiler-explorer-4f533aa: 305.369 seconds.
Time taken to run the queries on ./repositories/Django/thread3/djaodjin_djaodjin-saas/djaodjin-djaodjin-saas-213a532: 360.695 seconds.
Analysis failed for: ./repositories/Django/thread3/ecds_belfast-group-site/ecds-belfast-group-site-d385611 Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/ecds_belfast-group-site/ecds-belfast-group-site-d385611 -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/ecds_belfast-group-site/ecds-belfast-group-site-d385611: 349.162 seconds.
Time taken to run the queries on ./repositories/Django/thread3/edcNITD-website_edcNITD-website/edcNITD-website-edcNITD-website-29c6620: 285.506 seconds.
Analysis failed for: ./repositories/Django/thread3/f-klubben_stregsystemet/f-klubben-stregsystemet-af0efd8 Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/f-klubben_stregsystemet/f-klubben-stregsystemet-af0efd8 -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/f-klubben_stregsystemet/f-klubben-stregsystemet-af0efd8: 309.727 seconds.
Analysis failed for: ./repositories/Django/thread3/feincms_feincms3/feincms-feincms3-ffbf269 Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/feincms_feincms3/feincms-feincms3-ffbf269 -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/feincms_feincms3/feincms-feincms3-ffbf269: 289.567 seconds.
Time taken to run the queries on ./repositories/Django/thread3/feisuzhu_thbattle/feisuzhu-thbattle-17fd8b5: 383.868 seconds.
Time taken to run the queries on ./repositories/Django/thread3/freedomvote_freedomvote/freedomvote-freedomvote-33adb95: 221.577 seconds.
Analysis failed for: ./repositories/Django/thread3/frlan_partuniverse/frlan-partuniverse-17da8a1 Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/frlan_partuniverse/frlan-partuniverse-17da8a1 -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/frlan_partuniverse/frlan-partuniverse-17da8a1: 303.197 seconds.
Time taken to run the queries on ./repositories/Django/thread3/govtrack_govtrack.us-web/govtrack-govtrack.us-web-031ea63: 583.89 seconds.
Time taken to run the queries on ./repositories/Django/thread3/grai-io_grai-core/grai-io-grai-core-6d07538: 543.046 seconds.
Time taken to run the queries on ./repositories/Django/thread3/hackla-engage_engage-backend/hackla-engage-engage-backend-b9a2b08: 266.542 seconds.
Analysis failed for: ./repositories/Django/thread3/hasadna_OpenTrainCommunity/hasadna-OpenTrainCommunity-3c7a941 Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/hasadna_OpenTrainCommunity/hasadna-OpenTrainCommunity-3c7a941 -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/hasadna_OpenTrainCommunity/hasadna-OpenTrainCommunity-3c7a941: 301.929 seconds.
Analysis failed for: ./repositories/Django/thread3/hotosm_osm-export-tool/hotosm-osm-export-tool-28f58b3 Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/hotosm_osm-export-tool/hotosm-osm-export-tool-28f58b3 -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/hotosm_osm-export-tool/hotosm-osm-export-tool-28f58b3: 137.792 seconds.
Analysis failed for: ./repositories/Django/thread3/hse-mtc_dal/hse-mtc-dal-a77c010 Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/hse-mtc_dal/hse-mtc-dal-a77c010 -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/hse-mtc_dal/hse-mtc-dal-a77c010: 133.554 seconds.
Time taken to run the queries on ./repositories/Django/thread3/igemsoftware2017_SYSU-Software-2017/igemsoftware2017-SYSU-Software-2017-626cc24: 114.374 seconds.
Time taken to run the queries on ./repositories/Django/thread3/janatalab_pyensemble/janatalab-pyensemble-a6871ea: 85.214 seconds.
Time taken to run the queries on ./repositories/Django/thread3/jedie_PyInventory/jedie-PyInventory-ff210a0: 85.451 seconds.
Analysis failed for: ./repositories/Django/thread3/joausaga_cipe/joausaga-cipe-2460fab Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/joausaga_cipe/joausaga-cipe-2460fab -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/joausaga_cipe/joausaga-cipe-2460fab: 53.415 seconds.
Time taken to run the queries on ./repositories/Django/thread3/kimlimjustin_google-keep-clone/kimlimjustin-google-keep-clone-0c7c381: 58.586 seconds.
Time taken to run the queries on ./repositories/Django/thread3/lotrekagency_camomilla/lotrekagency-camomilla-a6bb63c: 70.712 seconds.
Time taken to run the queries on ./repositories/Django/thread3/lutris_website/lutris-website-8366ed2: 73.981 seconds.
Analysis failed for: ./repositories/Django/thread3/makepath_makestack/makepath-makestack-534d0c7 Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/makepath_makestack/makepath-makestack-534d0c7 -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/makepath_makestack/makepath-makestack-534d0c7: 63.426 seconds.
Time taken to run the queries on ./repositories/Django/thread3/modoboa_modoboa/modoboa-modoboa-f1f9e8a: 93.726 seconds.
Analysis failed for: ./repositories/Django/thread3/mozilla_fx-private-relay/mozilla-fx-private-relay-1fc4b99 Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/mozilla_fx-private-relay/mozilla-fx-private-relay-1fc4b99 -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/mozilla_fx-private-relay/mozilla-fx-private-relay-1fc4b99: 64.588 seconds.
Analysis failed for: ./repositories/Django/thread3/mrmap-community_mrmap/mrmap-community-mrmap-6490b3b Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/mrmap-community_mrmap/mrmap-community-mrmap-6490b3b -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/mrmap-community_mrmap/mrmap-community-mrmap-6490b3b: 54.034 seconds.
Analysis failed for: ./repositories/Django/thread3/nfoert_circles/nfoert-circles-7c5fe75 Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/nfoert_circles/nfoert-circles-7c5fe75 -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/nfoert_circles/nfoert-circles-7c5fe75: 40.796 seconds.
Time taken to run the queries on ./repositories/Django/thread3/nhsx_nhsx-website/nhsx-nhsx-website-17dd736: 60.142 seconds.
Analysis failed for: ./repositories/Django/thread3/nicbou_markdown-notes/nicbou-markdown-notes-a5d398b Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/nicbou_markdown-notes/nicbou-markdown-notes-a5d398b -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/nicbou_markdown-notes/nicbou-markdown-notes-a5d398b: 43.122 seconds.
Time taken to run the queries on ./repositories/Django/thread3/opencomputeproject_OCP-HM-MegaRAC_Community_Edition/opencomputeproject-OCP-HM-MegaRAC_Community_Edition-a713091: 95.199 seconds.
Time taken to run the queries on ./repositories/Django/thread3/overshard_timestrap/overshard-timestrap-a063302: 38.87 seconds.
Time taken to run the queries on ./repositories/Django/thread3/pablolmedorado_temat/pablolmedorado-temat-74580d7: 40.294 seconds.
Analysis failed for: ./repositories/Django/thread3/paul-wolf_djaq/paul-wolf-djaq-7a76129 Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/paul-wolf_djaq/paul-wolf-djaq-7a76129 -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/paul-wolf_djaq/paul-wolf-djaq-7a76129: 45.625 seconds.
Analysis failed for: ./repositories/Django/thread3/pinax_pinax-forums/pinax-pinax-forums-b8fff3d Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/pinax_pinax-forums/pinax-pinax-forums-b8fff3d -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/pinax_pinax-forums/pinax-pinax-forums-b8fff3d: 42.726 seconds.
Time taken to run the queries on ./repositories/Django/thread3/polyrabbit_WeCron/polyrabbit-WeCron-3907a4f: 52.486 seconds.
Time taken to run the queries on ./repositories/Django/thread3/pulp_pulpcore/pulp-pulpcore-0c76ccd: 66.668 seconds.
Time taken to run the queries on ./repositories/Django/thread3/raghavdhingra_HelloWorldWebsite/raghavdhingra-HelloWorldWebsite-df5f53e: 47.958 seconds.
Analysis failed for: ./repositories/Django/thread3/raunit-x_The-Gallery-of-Computation/raunit-x-The-Gallery-of-Computation-2b5d303 Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/raunit-x_The-Gallery-of-Computation/raunit-x-The-Gallery-of-Computation-2b5d303 -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/raunit-x_The-Gallery-of-Computation/raunit-x-The-Gallery-of-Computation-2b5d303: 38.775 seconds.
Time taken to run the queries on ./repositories/Django/thread3/retspen_webvirtcloud/retspen-webvirtcloud-3f23acb: 38.667 seconds.
Time taken to run the queries on ./repositories/Django/thread3/riso-tech_one-platform/RisoTech-Hub-one-platform-c37a3f6: 45.093 seconds.
Analysis failed for: ./repositories/Django/thread3/ristekoss_ulaskelas-backend/ristekoss-ulaskelas-backend-9fd6c8d Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/ristekoss_ulaskelas-backend/ristekoss-ulaskelas-backend-9fd6c8d -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/ristekoss_ulaskelas-backend/ristekoss-ulaskelas-backend-9fd6c8d: 47.557 seconds.
Time taken to run the queries on ./repositories/Django/thread3/sbenemerito_instaz/sbenemerito-instaz-17e07b8: 48.786 seconds.
Analysis failed for: ./repositories/Django/thread3/seuno-dev_candleaf/seuno-dev-candleaf-1f4e2b7 Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/seuno-dev_candleaf/seuno-dev-candleaf-1f4e2b7 -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/seuno-dev_candleaf/seuno-dev-candleaf-1f4e2b7: 48.26 seconds.
Analysis failed for: ./repositories/Django/thread3/shubhank-saxena_CiscoDevnetSIH2020_Kamikazey/shubhank-saxena-CiscoDevnetSIH2020_Kamikazey-dd9cef2 Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/shubhank-saxena_CiscoDevnetSIH2020_Kamikazey/shubhank-saxena-CiscoDevnetSIH2020_Kamikazey-dd9cef2 -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/shubhank-saxena_CiscoDevnetSIH2020_Kamikazey/shubhank-saxena-CiscoDevnetSIH2020_Kamikazey-dd9cef2: 76.476 seconds.
Time taken to run the queries on ./repositories/Django/thread3/techspaceusict_techspace-web/techspaceusict-techspace-web-8f26c82: 50.644 seconds.
Time taken to run the queries on ./repositories/Django/thread3/todi-2000_Quiz-App/todi-2000-Quiz-App-8881613: 44.102 seconds.
Analysis failed for: ./repositories/Django/thread3/tongochi_DEX/tongochi-DEX-bff390a Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/tongochi_DEX/tongochi-DEX-bff390a -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/tongochi_DEX/tongochi-DEX-bff390a: 46.59 seconds.
Analysis failed for: ./repositories/Django/thread3/torchbox_wagtail-grapple/torchbox-wagtail-grapple-438c9de Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/torchbox_wagtail-grapple/torchbox-wagtail-grapple-438c9de -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/torchbox_wagtail-grapple/torchbox-wagtail-grapple-438c9de: 37.492 seconds.
Time taken to run the queries on ./repositories/Django/thread3/uktrade_data-hub-api/uktrade-data-hub-api-8d1968c: 92.896 seconds.
Analysis failed for: ./repositories/Django/thread3/unscrollinc_unscroll/unscrollinc-unscroll-88168af Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/unscrollinc_unscroll/unscrollinc-unscroll-88168af -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/unscrollinc_unscroll/unscrollinc-unscroll-88168af: 48.287 seconds.
Time taken to run the queries on ./repositories/Django/thread3/usnistgov_NEMO/usnistgov-NEMO-f89c983: 56.572 seconds.
Analysis failed for: ./repositories/Django/thread3/vas3k_vas3k.club/vas3k-vas3k.club-841b316 Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/vas3k_vas3k.club/vas3k-vas3k.club-841b316 -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/vas3k_vas3k.club/vas3k-vas3k.club-841b316: 58.138 seconds.
Analysis failed for: ./repositories/Django/thread3/velis74_DynamicForms/velis74-DynamicForms-d1317cc Reason: Error: Command failed: npm start -- -s=./repositories/Django/thread3/velis74_DynamicForms/velis74-DynamicForms-d1317cc -l=python -t=11 -ct=3
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python-single-analysis.js:97:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Time taken to run the queries on ./repositories/Django/thread3/velis74_DynamicForms/velis74-DynamicForms-d1317cc: 45.603 seconds.
Time taken to run the queries on ./repositories/Django/thread3/visgence_timeclock/visgence-timeclock-f0973c0: 37.948 seconds.
Time taken to run the queries on ./repositories/Django/thread3/wlonk_wheretofind.me/wlonk-wheretofind.me-89ff41d: 34.398 seconds.
Time taken to run the queries on ./repositories/Django/thread3/yogeshojha_rengine/yogeshojha-rengine-2c9e250: 46.952 seconds.
Time taken to run the queries on ./repositories/Django/thread3/zuri-training_Proj_team_17_my_cms/zuri-training-Proj_team_17_my_cms-96645a5: 34.125 seconds.
Time taken to run the queries and generate the statistics: 39854.487 seconds.
