HTTP Error: sajjadium ctf-archives
Extraction or Cleanup Error: izj007_wechat Error: ENAMETOOLONG: name too long, open '/home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/izj007_wechat/izj007-wechat-0fef5b8/articles/[]-2023-3-20-肝毕设期间摸鱼一下，分享一个很早之前遇到的trick，将fastjson与原生反序列化结合，在1.2>
Extraction or Cleanup Error: JenifferWuUCLA_pulmonary-nodules-MaskRCNN Error: invalid relative path: JenifferWuUCLA-pulmonary-nodules-MaskRCNN-027c16c/Resources/TensorFlow-Tutorial/Deep_Learning_with_TensorFlow/0.12.0/Chapter05/5. MNIST最佳实践/../../Data_sets/MNIST_data/
HTTP Error: MicrosoftDocs azure-docs.zh-cn
HTTP Error: MicrosoftDocs azure-docs.ja-jp
HTTP Error: MicrosoftDocs azure-docs.zh-tw
HTTP Error: MicrosoftDocs azure-docs.es-es
Extraction or Cleanup Error: pmin91_DS_projects Error: invalid relative path: pmin91-DS_projects-a2bcfd0/01-MTA_Turnstile_EDA/../datastations.csv
HTTP Error: MicrosoftDocs azure-docs.ko-kr
HTTP Error: MicrosoftDocs azure-docs.de-de
HTTP Error: MicrosoftDocs azure-docs.pt-br
HTTP Error: dongwa quasar-docs-cn
HTTP Error: MicrosoftDocs azure-docs.fr-fr
Extraction or Cleanup Error: Koubae_Programming-CookBook Error: ENAMETOOLONG: name too long, symlink 'C RoadMap ... ' -> '/home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/Koubae_Programming-CookBook/Koubae-Programming-CookBook-e89935d/Programming Languages/C/fundamentals/roadmap/readme.md'
HTTP Error: MicrosoftDocs azure-docs.ru-ru
Extraction or Cleanup Error: Manish57-droid_python Error: ENAMETOOLONG: name too long, open '/home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/Manish57-droid_python/Manish57-droid-python-aacc6b1/import random when = ['A few years ago', 'Yesterday', 'Last night', 'A long time a>
HTTP Error: KOT-database KOT
HTTP Error: MicrosoftDocs azure-docs.it-it
HTTP Error: Louvivien letthemlive
HTTP Error: MicrosoftDocs azure-docs.pt-pt
HTTP Error: MicrosoftDocs azure-docs.tr-tr
HTTP Error: MicrosoftDocs azure-docs.nl-nl
HTTP Error: robmarkcole satellite-imagery-projects

Space used after downloading, extracting and cleaning up repos: 32 GB, Space used after first run of database creation: 37 GB, Space used after second run of database creation: 138 GB, Space used after manual run of database creation: 141 GB

Database Creation Error: apache_superset Error: Command failed: codeql database create ./repositories/Flask/apache_superset/apache-superset-75a7431-database --language=python --source-root ./repositories/Flask/apache_superset/apache-superset-75a7431
Initializing database at /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/apache_superset/apache-superset-75a7431-database.
Running build command: []
Finalizing database at /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/apache_superset/apache-superset-75a7431-database.
Killed

Database Creation Error: apache_airflow Error: Command failed: codeql database create ./repositories/Flask/apache_airflow/apache-airflow-9a65fea-database --language=python --source-root ./repositories/Flask/apache_airflow/apache-airflow-9a65fea
Initializing database at /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/apache_airflow/apache-airflow-9a65fea-database.
Running build command: []
Finalizing database at /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/apache_airflow/apache-airflow-9a65fea-database.
Killed

Database Creation Error: realpython_materials Error: Command failed: codeql database create ./repositories/Flask/realpython_materials/realpython-materials-f45d821-database --language=python --source-root ./repositories/Flask/realpython_materials/realpython-materials-f45d821
Initializing database at /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/realpython_materials/realpython-materials-f45d821-database.
Running build command: []
Finalizing database at /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/realpython_materials/realpython-materials-f45d821-database.
Killed

Database Creation Error: google_google-ctf Error: spawnSync /bin/sh ETIMEDOUT
Database Creation Error: simple-login_app Error: Command failed: codeql database create ./repositories/Flask/simple-login_app/simple-login-app-eb8f8ca-database --language=python --source-root ./repositories/Flask/simple-login_app/simple-login-app-eb8f8ca
Initializing database at /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/simple-login_app/simple-login-app-eb8f8ca-database.
Running build command: []
Killed

Database Creation Error: ...
...

Time taken to create the databases: 59403.687 seconds
Database Creation Error: gil9red_SimplePyScripts Error: spawnSync /bin/sh ENOBUFS
Database Creation Error: ryanmrestivo_red-team Error: spawnSync /bin/sh ENOBUFS
Database Creation Error: gistable_gistable Error: spawnSync /bin/sh ENOBUFS
Database Creation Error: Labs22_BlackServerOS Error: spawnSync /bin/sh ENOBUFS
Database Creation Error: Vijay-Yosi_biostack Error: spawnSync /bin/sh ENOBUFS
Database Creation Error: Mondego_pyreco Error: spawnSync /bin/sh ENOBUFS
Database Creation Error: aliostad_deep-learning-lang-detection Error: spawnSync /bin/sh ENOBUFS
Database Creation Error: Python000-class01_Python000-class01 Error: spawnSync /bin/sh ENOBUFS
Database Creation Error: academic-resources_stared-repos Error: spawnSync /bin/sh ENOBUFS
Database Creation Error: cndn_intelligent-code-completion Error: spawnSync /bin/sh ENOBUFS
Database Creation Error: shreejitverma_SDE-Interview-Prep Error: spawnSync /bin/sh ENOBUFS
Database Creation Error: gustcol_Canivete Error: spawnSync /bin/sh ENOBUFS
Database Creation Error: imfht_flaskapps Error: spawnSync /bin/sh ENOBUFS
Database Creation Error: LiuFang816_SALSTM_py_data Error: spawnSync /bin/sh ENOBUFS
Time taken to create the databases: 19917.519 seconds. Number of repositories processed: 697
Database Creation Error: gil9red_SimplePyScripts Error: spawnSync /bin/sh ENOBUFS
Database Creation Error: ryanmrestivo_red-team Error: spawnSync /bin/sh ENOBUFS
Database Creation Error: gistable_gistable Error: spawnSync /bin/sh ENOBUFS
Database Creation Error: Labs22_BlackServerOS Error: spawnSync /bin/sh ENOBUFS
Database Creation Error: Vijay-Yosi_biostack Error: spawnSync /bin/sh ENOBUFS
Database Creation Error: Mondego_pyreco Error: spawnSync /bin/sh ENOBUFS
Database Creation Error: aliostad_deep-learning-lang-detection Error: spawnSync /bin/sh ENOBUFS
Database Creation Error: Python000-class01_Python000-class01 Error: spawnSync /bin/sh ENOBUFS
Database Creation Error: academic-resources_stared-repos Error: spawnSync /bin/sh ENOBUFS
Database Creation Error: cndn_intelligent-code-completion Error: spawnSync /bin/sh ENOBUFS
Database Creation Error: shreejitverma_SDE-Interview-Prep Error: spawnSync /bin/sh ENOBUFS
Database Creation Error: gustcol_Canivete Error: spawnSync /bin/sh ENOBUFS
Database Creation Error: imfht_flaskapps Error: spawnSync /bin/sh ENOBUFS
Database Creation Error: LiuFang816_SALSTM_py_data Error: spawnSync /bin/sh ENOBUFS
Time taken to create the databases: 1120.843 seconds. Number of repositories processed: 14
Manual Database creation:
Timeout error: Mondego_pyreco

Analysis failed for: ./repositories/Flask/1u0Hun_SAReport/1u0Hun-SAReport-0f420d6 Reason: Error: Command failed: npm start -- -s=./repositories/Flask/1u0Hun_SAReport/1u0Hun-SAReport-0f420d6 -l=python
Compiling query plan for /home/878352/Session-Management-Analyser/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
[1/1] Found in cache: /home/878352/Session-Management-Analyser/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
Starting evaluation of asterius27/codeql-extra-queries-python/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
[1/1 eval 24.5s] Evaluation done; writing results to /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/1u0Hun_SAReport/1u0Hun-SAReport-0f420d6-results/flask_library_used_check.bqrs.
Shutting down query evaluator.
Compiling query plan for /home/878352/Session-Management-Analyser/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
[1/1] Found in cache: /home/878352/Session-Management-Analyser/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
Starting evaluation of asterius27/codeql-extra-queries-python/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
[1/1 eval 2.4s] Evaluation done; writing results to /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/1u0Hun_SAReport/1u0Hun-SAReport-0f420d6-results/django_library_used_check.bqrs.
Shutting down query evaluator.
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python.js:41
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python.js:41:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:42:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Analysis failed for: ./repositories/Flask/7Hxz233_CTF/7Hxz233-CTF-6dee195 Reason: Error: Command failed: npm start -- -s=./repositories/Flask/7Hxz233_CTF/7Hxz233-CTF-6dee195 -l=python
Compiling query plan for /home/878352/Session-Management-Analyser/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
[1/1] Found in cache: /home/878352/Session-Management-Analyser/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
Starting evaluation of asterius27/codeql-extra-queries-python/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
[1/1 eval 30.4s] Evaluation done; writing results to /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/7Hxz233_CTF/7Hxz233-CTF-6dee195-results/flask_library_used_check.bqrs.
Shutting down query evaluator.
Compiling query plan for /home/878352/Session-Management-Analyser/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
[1/1] Found in cache: /home/878352/Session-Management-Analyser/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
Starting evaluation of asterius27/codeql-extra-queries-python/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
[1/1 eval 2.8s] Evaluation done; writing results to /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/7Hxz233_CTF/7Hxz233-CTF-6dee195-results/django_library_used_check.bqrs.
Shutting down query evaluator.
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python.js:41
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python.js:41:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:42:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Analysis failed for: ./repositories/Flask/Ash515_DynamicHealthcareConsultingSystem/Ash515-DynamicHealthcareConsultingSystem-ea6dbed Reason: Error: Command failed: npm start -- -s=./repositories/Flask/Ash515_DynamicHealthcareConsultingSystem/Ash515-DynamicHealthcareConsultingSystem-ea6dbed -l=python
Compiling query plan for /home/878352/Session-Management-Analyser/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
[1/1] Found in cache: /home/878352/Session-Management-Analyser/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
Starting evaluation of asterius27/codeql-extra-queries-python/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
[1/1 eval 23.5s] Evaluation done; writing results to /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/Ash515_DynamicHealthcareConsultingSystem/Ash515-DynamicHealthcareConsultingSystem-ea6dbed-results/flask_library_used_check.bqrs.
Shutting down query evaluator.
Compiling query plan for /home/878352/Session-Management-Analyser/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
[1/1] Found in cache: /home/878352/Session-Management-Analyser/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
Starting evaluation of asterius27/codeql-extra-queries-python/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
[1/1 eval 2.3s] Evaluation done; writing results to /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/Ash515_DynamicHealthcareConsultingSystem/Ash515-DynamicHealthcareConsultingSystem-ea6dbed-results/django_library_used_check.bqrs.
Shutting down query evaluator.
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python.js:41
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python.js:41:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:42:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Analysis failed for: ./repositories/Flask/ClimateMind_climatemind-backend/ClimateMind-climatemind-backend-5f88c1a Reason: Error: Command failed: npm start -- -s=./repositories/Flask/ClimateMind_climatemind-backend/ClimateMind-climatemind-backend-5f88c1a -l=python
Compiling query plan for /home/878352/Session-Management-Analyser/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
[1/1] Found in cache: /home/878352/Session-Management-Analyser/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
Starting evaluation of asterius27/codeql-extra-queries-python/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
[1/1 eval 1m2s] Evaluation done; writing results to /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/ClimateMind_climatemind-backend/ClimateMind-climatemind-backend-5f88c1a-results/flask_library_used_check.bqrs.
Shutting down query evaluator.
Compiling query plan for /home/878352/Session-Management-Analyser/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
[1/1] Found in cache: /home/878352/Session-Management-Analyser/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
Starting evaluation of asterius27/codeql-extra-queries-python/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
[1/1 eval 5.2s] Evaluation done; writing results to /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/ClimateMind_climatemind-backend/ClimateMind-climatemind-backend-5f88c1a-results/django_library_used_check.bqrs.
Shutting down query evaluator.
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python.js:41
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python.js:41:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:42:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Analysis failed for: ./repositories/Flask/Crown-Commercial-Service_digitalmarketplace-supplier-frontend/Crown-Commercial-Service-digitalmarketplace-supplier-frontend-05c35ab Reason: Error: Command failed: npm start -- -s=./repositories/Flask/Crown-Commercial-Service_digitalmarketplace-supplier-frontend/Crown-Commercial-Service-digitalmarketplace-supplier-frontend-05c35ab -l=python
Compiling query plan for /home/878352/Session-Management-Analyser/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
[1/1] Found in cache: /home/878352/Session-Management-Analyser/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
Starting evaluation of asterius27/codeql-extra-queries-python/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
[1/1 eval 25s] Evaluation done; writing results to /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/Crown-Commercial-Service_digitalmarketplace-supplier-frontend/Crown-Commercial-Service-digitalmarketplace-supplier-frontend-05c35ab-results/flask_library_used_check.bqrs.
Shutting down query evaluator.
Compiling query plan for /home/878352/Session-Management-Analyser/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
[1/1] Found in cache: /home/878352/Session-Management-Analyser/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
Starting evaluation of asterius27/codeql-extra-queries-python/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
[1/1 eval 2.5s] Evaluation done; writing results to /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/Crown-Commercial-Service_digitalmarketplace-supplier-frontend/Crown-Commercial-Service-digitalmarketplace-supplier-frontend-05c35ab-results/django_library_used_check.bqrs.
Shutting down query evaluator.
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python.js:41
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python.js:41:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:42:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Analysis failed for: ./repositories/Flask/CuiYongen_DuplicateChecking/CuiYongen-DuplicateChecking-84a4a1a Reason: Error: Command failed: npm start -- -s=./repositories/Flask/CuiYongen_DuplicateChecking/CuiYongen-DuplicateChecking-84a4a1a -l=python
Compiling query plan for /home/878352/Session-Management-Analyser/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
[1/1] Found in cache: /home/878352/Session-Management-Analyser/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
Starting evaluation of asterius27/codeql-extra-queries-python/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
[1/1 eval 42.7s] Evaluation done; writing results to /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/CuiYongen_DuplicateChecking/CuiYongen-DuplicateChecking-84a4a1a-results/flask_library_used_check.bqrs.
Shutting down query evaluator.
Compiling query plan for /home/878352/Session-Management-Analyser/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
[1/1] Found in cache: /home/878352/Session-Management-Analyser/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
Starting evaluation of asterius27/codeql-extra-queries-python/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
[1/1 eval 3.8s] Evaluation done; writing results to /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/CuiYongen_DuplicateChecking/CuiYongen-DuplicateChecking-84a4a1a-results/django_library_used_check.bqrs.
Shutting down query evaluator.
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python.js:41
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python.js:41:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:42:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Analysis failed for: ./repositories/Flask/DengBoCong_nlp-dialogue/DengBoCong-nlp-dialogue-03cadb6 Reason: Error: Command failed: npm start -- -s=./repositories/Flask/DengBoCong_nlp-dialogue/DengBoCong-nlp-dialogue-03cadb6 -l=python
Compiling query plan for /home/878352/Session-Management-Analyser/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
[1/1] Found in cache: /home/878352/Session-Management-Analyser/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
Starting evaluation of asterius27/codeql-extra-queries-python/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
[1/1 eval 42.2s] Evaluation done; writing results to /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/DengBoCong_nlp-dialogue/DengBoCong-nlp-dialogue-03cadb6-results/flask_library_used_check.bqrs.
Shutting down query evaluator.
Compiling query plan for /home/878352/Session-Management-Analyser/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
[1/1] Found in cache: /home/878352/Session-Management-Analyser/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
Starting evaluation of asterius27/codeql-extra-queries-python/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
[1/1 eval 3.8s] Evaluation done; writing results to /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/DengBoCong_nlp-dialogue/DengBoCong-nlp-dialogue-03cadb6-results/django_library_used_check.bqrs.
Shutting down query evaluator.
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python.js:41
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python.js:41:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:42:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Analysis failed for: ./repositories/Flask/Flexget_Flexget/Flexget-Flexget-673f046 Reason: Error: Command failed: npm start -- -s=./repositories/Flask/Flexget_Flexget/Flexget-Flexget-673f046 -l=python
Compiling query plan for /home/878352/Session-Management-Analyser/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
[1/1] Found in cache: /home/878352/Session-Management-Analyser/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
Starting evaluation of asterius27/codeql-extra-queries-python/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
[1/1 eval 51.8s] Evaluation done; writing results to /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/Flexget_Flexget/Flexget-Flexget-673f046-results/flask_library_used_check.bqrs.
Shutting down query evaluator.
Compiling query plan for /home/878352/Session-Management-Analyser/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
[1/1] Found in cache: /home/878352/Session-Management-Analyser/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
Starting evaluation of asterius27/codeql-extra-queries-python/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
[1/1 eval 4.5s] Evaluation done; writing results to /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/Flexget_Flexget/Flexget-Flexget-673f046-results/django_library_used_check.bqrs.
Shutting down query evaluator.
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python.js:41
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python.js:41:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:42:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Analysis failed for: ./repositories/Flask/Fluent-networks_floranet/Fluent-networks-floranet-f025825 Reason: Error: Command failed: npm start -- -s=./repositories/Flask/Fluent-networks_floranet/Fluent-networks-floranet-f025825 -l=python
Compiling query plan for /home/878352/Session-Management-Analyser/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
[1/1] Found in cache: /home/878352/Session-Management-Analyser/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
Starting evaluation of asterius27/codeql-extra-queries-python/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
[1/1 eval 38.4s] Evaluation done; writing results to /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/Fluent-networks_floranet/Fluent-networks-floranet-f025825-results/flask_library_used_check.bqrs.
Shutting down query evaluator.
Compiling query plan for /home/878352/Session-Management-Analyser/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
[1/1] Found in cache: /home/878352/Session-Management-Analyser/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
Starting evaluation of asterius27/codeql-extra-queries-python/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
[1/1 eval 3.5s] Evaluation done; writing results to /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/Fluent-networks_floranet/Fluent-networks-floranet-f025825-results/django_library_used_check.bqrs.
Shutting down query evaluator.
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python.js:41
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python.js:41:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:42:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Analysis failed for: ./repositories/Flask/FreeTAKTeam_FreeTakServer/FreeTAKTeam-FreeTakServer-f73262b Reason: Error: Command failed: npm start -- -s=./repositories/Flask/FreeTAKTeam_FreeTakServer/FreeTAKTeam-FreeTakServer-f73262b -l=python
Compiling query plan for /home/878352/Session-Management-Analyser/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
[1/1] Found in cache: /home/878352/Session-Management-Analyser/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
Starting evaluation of asterius27/codeql-extra-queries-python/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
[1/1 eval 39.9s] Evaluation done; writing results to /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/FreeTAKTeam_FreeTakServer/FreeTAKTeam-FreeTakServer-f73262b-results/flask_library_used_check.bqrs.
Shutting down query evaluator.
Compiling query plan for /home/878352/Session-Management-Analyser/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
[1/1] Found in cache: /home/878352/Session-Management-Analyser/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
Starting evaluation of asterius27/codeql-extra-queries-python/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
[1/1 eval 3.6s] Evaluation done; writing results to /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/FreeTAKTeam_FreeTakServer/FreeTAKTeam-FreeTakServer-f73262b-results/django_library_used_check.bqrs.
Shutting down query evaluator.
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python.js:41
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python.js:41:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:42:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Analysis failed for: ./repositories/Flask/IBM-EPBL_IBM-Project-54090-1661594240/IBM-EPBL-IBM-Project-54090-1661594240-49ecb75 Reason: Error: Command failed: npm start -- -s=./repositories/Flask/IBM-EPBL_IBM-Project-54090-1661594240/IBM-EPBL-IBM-Project-54090-1661594240-49ecb75 -l=python
Compiling query plan for /home/878352/Session-Management-Analyser/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
[1/1] Found in cache: /home/878352/Session-Management-Analyser/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
Starting evaluation of asterius27/codeql-extra-queries-python/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
[1/1 eval 41s] Evaluation done; writing results to /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/IBM-EPBL_IBM-Project-54090-1661594240/IBM-EPBL-IBM-Project-54090-1661594240-49ecb75-results/flask_library_used_check.bqrs.
Shutting down query evaluator.
Compiling query plan for /home/878352/Session-Management-Analyser/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
[1/1] Found in cache: /home/878352/Session-Management-Analyser/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
Starting evaluation of asterius27/codeql-extra-queries-python/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
[1/1 eval 3.6s] Evaluation done; writing results to /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/IBM-EPBL_IBM-Project-54090-1661594240/IBM-EPBL-IBM-Project-54090-1661594240-49ecb75-results/django_library_used_check.bqrs.
Shutting down query evaluator.
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python.js:41
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python.js:41:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:42:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Analysis failed for: ./repositories/Flask/JunManYuanLong_TcloudServer/JunManYuanLong-TcloudServer-6b26d7d Reason: Error: Command failed: npm start -- -s=./repositories/Flask/JunManYuanLong_TcloudServer/JunManYuanLong-TcloudServer-6b26d7d -l=python
Compiling query plan for /home/878352/Session-Management-Analyser/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
[1/1] Found in cache: /home/878352/Session-Management-Analyser/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
Starting evaluation of asterius27/codeql-extra-queries-python/Flask_Queries/Flask-login-is-used-check/flask_library_used_check.ql.
[1/1 eval 35.9s] Evaluation done; writing results to /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/JunManYuanLong_TcloudServer/JunManYuanLong-TcloudServer-6b26d7d-results/flask_library_used_check.bqrs.
Shutting down query evaluator.
Compiling query plan for /home/878352/Session-Management-Analyser/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
[1/1] Found in cache: /home/878352/Session-Management-Analyser/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
Starting evaluation of asterius27/codeql-extra-queries-python/Django_Queries/Django-auth-is-used-check/django_library_used_check.ql.
[1/1 eval 3.4s] Evaluation done; writing results to /home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/repositories/Flask/JunManYuanLong_TcloudServer/JunManYuanLong-TcloudServer-6b26d7d-results/django_library_used_check.bqrs.
Shutting down query evaluator.
file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python.js:41
        throw new Error("None of the supported libraries/frameworks is used");
              ^

Error: None of the supported libraries/frameworks is used
    at pythonAnalysis (file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/python.js:41:15)
    at file:///home/878352/Session-Management-Analyser/SessionManagementAnalyserApp/app.js:42:5
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.8.0

Second run (first one got stuck at https://github.com/LiuFang816/SALSTM_py_data):

